
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract QueueStore {
    // Contract can have an instance variables.
    // In this example instance variable `timestamp` is used to store the time of `constructor` or `touch`
    // function call
    string[] namesOfPeople;

    // Contract can have a `constructor` – function that will be called when contract will be deployed to the blockchain.
    // In this example constructor adds current time to the instance variable.
    // All contracts need call tvm.accept(); for succeeded deploy
    constructor() public {
        
        addLine("Nikola");
        addLine("Dima");
        addLine("Artem");
        addLine("Daniil");
        // tvm.accept();
    }

    function addLine(string s) public {
        namesOfPeople.push(s);
        // tvm.accept();
    }

    function getUser() public view returns (string) {
        string stringPeopleInLine;
        
        for (uint256 index = 0; index < namesOfPeople.length; index++) {
            if(index == namesOfPeople.length - 1){
                stringPeopleInLine +=  namesOfPeople[index];
            }else{
                stringPeopleInLine +=  namesOfPeople[index] + ", " ;
            }
        }
        // tvm.accept();
        return stringPeopleInLine;
   }

    function getLinesCount() public view returns (uint) {
        // tvm.accept();
        return namesOfPeople.length;
    }

    function getLastLine() public view returns (string) {
        // tvm.accept();
        return namesOfPeople[namesOfPeople.length-1];
    }

}
