
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract map_opt {
    
    mapping (uint => uint) myMap;

    constructor() public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
        myMap[4] = 22;
        myMap[1] = 24;
        myMap[3] = 26;
        myMap[2] = 1;
        myMap[23] = 262;
        myMap[12] = 11;
    }

    function renderHelloWorld () public pure returns (string) {
        return 'helloWorld';
    }

    function getList() public returns (uint[]){
        tvm.accept();
        optional(uint, uint) currentOpt = myMap.min(); // 
        uint[] resArr;

        while (currentOpt.hasValue()){
            (uint key, uint val) = currentOpt.get();
            resArr.push(val);
            currentOpt = myMap.next(key);
        }
        return resArr;
    }
}
