
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "storageInt.sol";

contract clientForStorage {
    uint32 public sample1;
    uint32 sample2;

    function renderHelloWorld1 () public pure returns (string) {
        return 'helloWorld';
    }

    function renderHelloWorld2 () public pure returns (string) {
        tvm.accept();
        return 'helloWorld';
    }

    function store(storageInt currentStorage, uint val) public pure {
        tvm.accept();
        currentStorage.storeUInt(val);
    }
}
